quiet: true
skip-check:
  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2
  # Ensure that a user for the container has been created
  - CKV_DOCKER_3
  - CKV_GHA_7
  - CKV_K8S_8
  - CKV_K8S_11
  - CKV_K8S_13
  - CKV_K8S_15
  - CKV_K8S_20
  - CKV_K8S_21
  - CKV_K8S_22
  - CKV_K8S_23
  - CKV_K8S_28
  - CKV_K8S_29
  - CKV_K8S_31
  - CKV_K8S_37
  - CKV_K8S_38
  - CKV_K8S_40
  - CKV_K8S_43
