name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'workflow run'
        required: true
        default: 'true'

permissions:
  contents: write

jobs:
  build-and-push-docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/image-tag-updater:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Set short sha
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Run the Container
        env:
          TARGET_PATH: charts/somaz/api
          NEW_TAG: ${{ steps.vars.outputs.short_sha }}
          TARGET_VALUES_FILE: dev1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER_NAME: somaz
          GIT_USER_EMAIL: genius5711@gmail.com
        run: |
          docker run \
          --env TARGET_PATH="${{ env.TARGET_PATH}}" \
          --env NEW_TAG="${{ env.NEW_TAG }}" \
          --env TARGET_VALUES_FILE="${{ env.TARGET_VALUES_FILE }}" \
          --env GITHUB_TOKEN="${{ env.GITHUB_TOKEN }}" \
          --env GIT_USER_NAME="${{ env.GIT_USER_NAME }}" \
          --env GIT_USER_EMAIL="${{ env.GIT_USER_EMAIL }}" \
          --volume ${{ github.workspace }}:/usr/src \
          --rm ${{ env.TEST_TAG }}
